---
title: "Tidy chemical data"
author: "Nan Xiao <<https://nanx.me>>"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: false
    css: custom.css
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Tidy chemical data}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE
)

run <- if (tidychem::is_installed_rdkit()) TRUE else FALSE
knitr::opts_chunk$set(eval = run)
```

## Introduction

The `tidychem` package offers a lightweight R interface for accessing RDKit via the [RDKit Python API](http://www.rdkit.org/docs/api/).

## Walkthrough

```{r}
library("tidychem")
```

```{r}
mols <- "smi-multiple.smi" %>%
  tidychem_example() %>%
  read_smiles()

# ECFP4
mols %>% fp_morgan()

# similarity
# mols %>% fp_morgan %>% sim_tanimoto

# matrix
mols %>% fp_morgan(explicit = TRUE)
```

```{r}
df <- "logd74.tsv" %>%
  tidychem_example() %>%
  read_tsv()
y <- df$logD7.4
mols <- df$SMILES %>% parse_smiles()
mols

# matrix of 2D/3D descriptors
x <- mols %>% desc_2d()
x
x[which(is.na(x))] <- 0
```

```{r}
library("glmnet")

cvfit <- cv.glmnet(x, y)
plot(cvfit)

fit <- glmnet(x, y)
plot(fit)
head(coef(fit, s = cvfit$lambda.min, exact = TRUE), n = 30)
```
